#! /usr/bin/env bash

#ctags --languages=Ruby --regex-Ruby='/^[ \t]*(named_scope|has_many)[ \t]+:([a-zA-Z0-9_]+)/\2/' --regex-Ruby='/^[ \t]*event[ \t]+:([a-zA-Z0-9_]+)/\1!/' $*
#ctags -R --sort=yes $*

find $* \
    \( \
        -name '.DS_Store' -or \
        -name '.tmp_*~' -or \
        -name '*.pdf' -or \
        -name '*.jpg' -or \
        -name '*.png' -or \
        -name '*.swf' -or \
        -name '*.gif' -or \
        -name '*.ico' -or \
        -name '*.swp' -or \
        -name '.gitignore' -or \
        -name '*.swd' -or \
        -name '*.swo' \
    \) -prune -or \
    \( \
         -path '*/.svn/*' -or \
         -path '*/migrate/*' -or \
         -path '*/.git/*' -or \
         -path '*/tmp/*' -or \
         -path '*/performance/*' -or \
         -path '*/tax_chart/*' -or \
         -path '*/coverage/*' \
     \) -prune -or \
     -type f -print | \
ctags -R --sort=yes -L -
