#! /usr/bin/env python

import socket

s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)

# wake up a windows box in chengxuan office
# to wake other computer, just replace the mac address 
#mac_addr = '\xf4\x6d\x04\x56\x73\xbe'
mac_addr = '\x00\x11\x32\x16\x7b\x2c'
s.sendto('\xff'*6 + mac_addr*16, ("255.255.255.255", 7))
s.close()

